FROM ll/gamesvr

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/gamesvr/dinodday/" SERVER_NAME="ll/gamesvr-dinodday" 

COPY ./files/ /gamesvr/dinodday/

WORKDIR /gamesvr/dinodday/

CMD ["/bin/bash"]

#TODO:
#get /gamesvr/dinodday/ <=- ftp.content.lan/fastDownloads/dinodday/