FROM ll/gamesvr

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/gamesvr/dods/" SERVER_NAME="ll/gamesvr-dods" 

COPY ./files/ /gamesvr/dods/

WORKDIR /gamesvr/dods/

CMD ["/bin/bash"]

#TODO:
#get /gamesvr/dods/ <=- ftp.content.lan/fastDownloads/dods/