FROM ll/gamesvr:srcds

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/gamesvr/tf2/" SERVER_NAME="ll/gamesvr-tf2"

COPY ./files/ /gamesvr/tf2/

WORKDIR /gamesvr/tf2/

#TODO:
#get ftp contents -=> content.lan/fastDownloads/tf2/