FROM ll/gamesvr:srcds

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/gamesvr/svencoop/" SERVER_NAME="ll/gamesvr-svencoop-freeplay"

COPY ./files/ /gamesvr/svencoop/

RUN `##Set up container enviorment##` && \
    useradd --home /gamesvr/svencoop/ --create-home gamesvr-svencoop-freeplay

USER gamesvr-svencoop-freeplay

WORKDIR /gamesvr/svencoop/
