FROM nginx

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/usr/share/nginx/html/" SERVER_NAME="ll/websvr-content.lan"

COPY ./files/ /usr/share/nginx/html/

WORKDIR /usr/share/nginx/html/