FROM ll/gamesvr:steamcmd

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/gamesvr/blackmesa/" SERVER_NAME="ll/gamesvr-blackmesa" 

COPY ./files/ /gamesvr/blackmesa/

WORKDIR /gamesvr/blackmesa/

CMD ["/bin/bash"]