FROM ll/gamesvr-csgo

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV SERVER_MAINTAINER "Laclede's LAN"
ENV SERVER_NAME "LL Counter-Strike GO Freeplay Server"

RUN cd `mktemp -d` `#Make a temporary directory#` && \
	git clone https://github.com/LacledesLAN/gamesvr-srcds.linux && \
	rm -rf *.git && \
	cd `ls -A | head -1` `#cd into repo directory#` && \
	rm -f *.md && \
	cp -r * /gameservers/csgo/ `#copy downloaded files to their destination#` && \
	cd `mktemp -d` `#Make a temporary directory#` && \
	git clone https://github.com/LacledesLAN/gamesvr-srcds-csgo && \
	rm -rf *.git && \
	cd `ls -A | head -1` `#cd into repo directory#` && \
	rm -f *.md && \
	cp -r * /gameservers/csgo/ `#copy downloaded files to their destination#` && \
	rm -fr /tmp/* `#Clean out temp directory to save space#` 

WORKDIR /gameservers/