FROM ll/gamesvr

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/gamesvr/csgo/" SERVER_NAME="ll/gamesvr-csgo" 

COPY . /gamesvr/csgo/

WORKDIR /gamesvr/csgo/

CMD ["/bin/bash"]

#TODO:
#get /gamesvr/csgo/ <=- ftp.content.lan/fastDownloads/csgo/