FROM ll/gamesvr-garrysmod

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV HOME="/gamesvr/garrysmod/" SERVER_NAME="ll/gamesvr-garrysmod-freeplay"

COPY ./files/ /gamesvr/garrysmod/

RUN `##Set up container enviorment##` && \
    useradd --home /gamesvr/garrysmod/ --create-home gamesvr-garrysmod-freeplay

USER gamesvr-garrysmod-freeplay

WORKDIR /gamesvr/garrysmod/